services:
  postgres:
    build: .
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
    restart: unless-stopped
    networks:
      - pgtest_network
    ports:
      - "5432:5432"

  sut:
    build: ./tests
    command:
      - "/tests/wait-for-postgres.sh"
      - "psql"
      - "postgresql://postgres:postgres@postgres:5432/postgres"
      - "-a"
      - "-f"
      - "/tests/create_extensions.sql"
    restart: 'no'
    depends_on:
      - postgres
    networks:
      - pgtest_network

networks:
  pgtest_network:
    driver: bridge
