name: Create and publish Docker images

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  schedule:
    # postgis/postgis update schedule is '15 5 * * 1'
    # https://github.com/postgis/docker-postgis/blob/master/.github/workflows/main.yml
    - cron: '15 7 * * 1'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  TEST_TAG: ${{ github.repository }}:test
  COMPOSE_FILE: ./docker-compose.test.yml
  LATEST_TAG: 16-3.4

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read

    strategy:
      fail-fast: false
      matrix:
        postgres: [16]
        postgis: ['3.4']

    env:
      BASE_IMAGE_TAG: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: ${{ env.BASE_IMAGE_TAG }}

      - name: Push to registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
